### ISSUE TITLE
Value of type 'RBSResponse' has no subscripts

### ISSUE THREAD

**Issue by HarryF514** [wesgood/RBSManager#15]
When I cloned the repo and try to do a build. 

![image](https://user-images.githubusercontent.com/4098187/101934817-1d7bd300-3bac-11eb-92b8-9c826035e1d2.png)

**Comment by HarryF514** [comment]
RBSManager_Example Group
Swift Compiler Error Group
/Users/harry/Downloads/RBSManager/Example/RBSManager/ViewController.swift:139:42: Value of type 'RBSResponse' has no subscripts
/Users/harry/Downloads/RBSManager/Example/RBSManager/ViewController.swift:145:44: Value of type 'RBSResponse' has no subscripts
/Users/harry/Downloads/RBSManager/Example/RBSManager/ViewController.swift:151:43: Value of type 'RBSResponse' has no subscripts
/Users/harry/Downloads/RBSManager/Example/RBSManager/ViewController.swift:233:45: Value of type 'PoseMessage' has no member 'x'
/Users/harry/Downloads/RBSManager/Example/RBSManager/ViewController.swift:240:45: Value of type 'PoseMessage' has no member 'y'
/Users/harry/Downloads/RBSManager/Example/RBSManager/ViewController.swift:247:49: Value of type 'PoseMessage' has no member 'theta'
/Users/harry/Downloads/RBSManager/Example/RBSManager/ViewController.swift:339:56: Value of type 'PoseMessage' has no member 'x'
/Users/harry/Downloads/RBSManager/Example/RBSManager/ViewController.swift:340:56: Value of type 'PoseMessage' has no member 'y'
/Users/harry/Downloads/RBSManager/Example/RBSManager/ViewController.swift:341:60: Value of type 'PoseMessage' has no member 'theta'
/Users/harry/Downloads/RBSManager/Example/RBSManager/ViewController.swift:346:96: Value of type 'PoseMessage' has no member 'theta'

**Comment by wesgood** [comment]
The master branch has some of my work in progress. I think what you're seeing here is the move to the RBSResponse object that I haven't yet completed, but plan to do so shortly. If the pod will work for your usecase, I suggest trying that first.

If you'd like to use the master branch and fix the issue, `RBSResponse` has a number of properties, including one for the raw dictionary data that the subscript look up can use.

**Comment by wesgood** [comment]
Hello, I have made some changes and corrected some issues. I had a problem pushing to GitHub but that's been resolved. The latest version seems to work with my robot project. CocoaPod v0.4 has been published as well. I'll close the ticket but feel free to reopen if you see other issues.
