### ISSUE TITLE
Migrate to Swift Package Manager

### ISSUE THREAD

**Issue by agcoesbenr** [wesgood/RBSManager#16]
I would like to migrate this to SPM and make a PR.

Should we keep the support for CocoaPods?

**Comment by wesgood** [comment]
Yes if you'd like please go ahead! We are moving to that at work but I have not had the time to implement it here.

**Comment by wesgood** [comment]
Also CocoaPod support should probably stay in, unless that causes conflicts (so far I haven't heard about that)

**Comment by agcoesbenr** [comment]
I'll make a PR.

**Comment by agcoesbenr** [comment]
Hi. I have made the PR.

The example åroject still uses cocoa pods as I did not want to change that. But let me know if I should migrate that to SPM.

**Comment by agcoesbenr** [comment]
The PR has been merged.
