### ISSUE TITLE
Support for std_msgs::String

### ISSUE THREAD

**Issue by juliangaal** [wesgood/RBSManager#2]
As far as I can tell, you don't support std::msgs/String in RBSMessages. Any plans to support it? Thanks!

**Comment by wesgood** [comment]
I target messages that users request, simply due to the time I have available. Now that I know there is more interest for the standard message package, I'll look into it further. Thanks for the note! If there are other types you'd like to see for sure, please let me know (although at this point I will likely try to get as many of the standard messages as possible).

**Comment by juliangaal** [comment]
Great, thank you. 

I'm building an app, from which I can send voice commands to ROS. For now, what would you recommend? Just use geometry_msgs::Twist and "abuse" the frame_id as my command string? Do you know if there's a limit on character length for the frame id?

**Comment by wesgood** [comment]
I think you can build your own message type if you want to use that instead. Swift should be able to make use of any class in your project globally. Take a look at any of the simple classes like PointMessage and adjust the properties to suit. You just need to inherit from RBSMessage and conform to the ObjectMapper protocol. If you name your class something specific to your project, there shouldn't be any naming collisions later if I add a new type (I'll be using something generic like StringMessage, for example).

**Comment by juliangaal** [comment]
I thought about that. If it works well, I'll make a PR (granted, I continue this project I'm working on)

Is there a way for me to use the HeaderMessage directly? Or is it embedded in others? Because choosing `MessageClass: HeaderMessage.self` results in an error

**Comment by wesgood** [comment]
It seems I was sloppy on some of the message classes and they are not marked as public. If you change that, you should have access. Take a look at `TwistMessage` for an example on using nested message types (it's only the constructor that is different)

**Comment by juliangaal** [comment]
I think the same happened with Time Message

**Comment by juliangaal** [comment]
Created pull request #3 

Adds Message Type StringMessage
Makes TimeMessage and HeaderMessage public

**Comment by wesgood** [comment]
Thank you for supplying the new StringMessage class. I have included it in the new version 0.3.0. I've also included a Python script to generate message files on demand. I'll close this issue but feel free to open it again if you have questions.

**Comment by juliangaal** [comment]
great idea with the Python script!
