### ISSUE TITLE
build in Xcode10 get error

### ISSUE THREAD

**Issue by WeJay** [wesgood/RBSManager#4]
hi, I recently update my iPhone to IOS12, Xcode 10. I rebuild RBSManager project and get this error. Can someone help me solve this question?

![image](https://user-images.githubusercontent.com/17249978/45793371-51653800-bcc4-11e8-8770-a6e8b317f7bd.png)

**Comment by wesgood** [comment]
I have not spent any time with iOS12 or Xcode 10 but Linker command errors are often generic and provide additional info if you select them from the side list. It might complain about a missed file. If there is nothing, clean the project and try again.

**Comment by WeJay** [comment]
Ok, I see this info, and I use command+shift+k clean project and rebuild it. I still can't solve! 
￼￼
![image](https://user-images.githubusercontent.com/17249978/45794766-d05d6f00-bcca-11e8-96d0-b89e03cced76.png)

**Comment by wesgood** [comment]
The line above the highlighted line indicates an issue with architecture arm64. Do you have any libraries or frameworks in your project that might not include arm64 support? I haven't run into that on this project but I've seen it with other frameworks.

**Comment by WeJay** [comment]
Hello I fixed the problem. I run "pod cache clear --all" and "pod update". Then I fix some code issue from swift 4.1 to swift 4.2. Rebuild it, and it can work.
Thank you for your reply.
