### ISSUE TITLE
Support for geometry_msgs/TwistStamped

### ISSUE THREAD

**Issue by jpack2015** [wesgood/RBSManager#6]
Would it be possible to support messages with a header, such as geometry_msgs/TwistStamped?

**Comment by wesgood** [comment]
Yes, if you look at a message like TwistMessage at https://github.com/wesgood/RBSManager/blob/master/RBSManager/Classes/Messages/Geometry/TwistMessage.swift you can see how to structure the message object when it contains a second message type. The setup is slightly different as it requires a new init method but if you change the variables, it should work the same. I suggest naming it like TwistStampedMessage

**Comment by jpack2015** [comment]
#7
